version: "3"

services:
  webserver:
    build:
      context: ./docker/bin/webserver
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql
    volumes:
      - ./:/var/www/html
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/config/vhosts:/etc/apache2/sites-enabled
      - ./docker/logs/apache2:/var/log/apache2
  mysql:
    image: mysql:5.7
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
      - ./docker/logs/mysql:/var/log/mysql
      - ./docker/config/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: avnida123
      MYSQL_DATABASE: avnida
      MYSQL_USER: avnida
      MYSQL_PASSWORD: avnida123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: 'always'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes:
      - /sessions